  - name: delete app directory
    ansible.builtin.file:
      path: "{{ app_location }}"
	    state: ansent 
   #ignore_errors: yes 
	
#if there its delete not there errors come, if not there we can give ignore_error

  - name: create app directory
    ansible.builtin.file:
      path: "{{ app_location }}"
	    state: directory 
   
  - name: download and extract code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: " {{ app_location }}"
      remote_src: yes  